jwt.secret: javainuse
application.data.dir: C:\Users\Enigma-Camp\Pictures\api
server.port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/enigma_inventory
        username: root
        password:
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    messages.basename: i18n/messages
    servlet.multipart:
        max-file-size: 300KB
        max-request-size: 300KB
springdoc:
    swagger-ui.path: /api-docs